[build]
  # Pas de commande de build car fichiers HTML statiques
  command = ""
  # Dossier contenant vos fichiers HTML
  publish = "frontend"

[[redirects]]
  from = "/api/*"
  to = "https://gmao-sakete-ifangni-1.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"